"""构建期补丁：TG 回复打字机模式（流式接收 → 按句切段 → 逐句发送，句间 typing）。
Docker 构建时对 heartbeat.py 打补丁，打完即删。本地运行则先执行 python patch_typewriter.py。
"""

NEW_FUNC = 'async def _ask_llm_stream_sentences(client, prompt, temperature=0.8):\n    """流式调用主对话模型，按句子异步产出文本（打字机模式专用）。"""\n    model_name = os.environ.get("CHAT_MODEL_NAME", "gpt-4o-mini")\n    messages = [{"role": "user", "content": prompt}]\n    queue = asyncio.Queue()\n    loop = asyncio.get_running_loop()\n\n    def _stream_worker():\n        try:\n            kwargs = dict(model=model_name, messages=messages, temperature=temperature, stream=True)\n            try:\n                stream = client.chat.completions.create(**kwargs)\n            except Exception as e:\n                # 部分模型（如 kimi-k3）只允许 temperature=1，自动降级重试\n                if "temperature" in str(e).lower():\n                    kwargs["temperature"] = 1\n                    stream = client.chat.completions.create(**kwargs)\n                else:\n                    raise\n            for chunk in stream:\n                try:\n                    delta = chunk.choices[0].delta.content\n                except Exception:\n                    delta = None\n                if delta:\n                    loop.call_soon_threadsafe(queue.put_nowait, delta)\n        except Exception as e:\n            loop.call_soon_threadsafe(queue.put_nowait, e)\n        finally:\n            loop.call_soon_threadsafe(queue.put_nowait, None)\n\n    threading.Thread(target=_stream_worker, daemon=True).start()\n\n    buffer = ""\n    pattern = re.compile(r\'[^。！？!?…\\n]*[。！？!?…\\n]+\')\n    while True:\n        item = await queue.get()\n        if item is None:\n            break\n        if isinstance(item, Exception):\n            raise item\n        buffer += item\n        while True:\n            m = pattern.match(buffer)\n            if not m:\n                break\n            sent = m.group(0).strip()\n            buffer = buffer[m.end():]\n            if sent:\n                yield sent\n        if len(buffer) > 400:  # 保险：过长无句读时强制吐出\n            yield buffer.strip()\n            buffer = ""\n    if buffer.strip():\n        yield buffer.strip()'
OLD_BLOCK = '                        reply = await _ask_llm_async(client, prompt, temperature=0.8)\n\n                        if reply:\n                            await asyncio.to_thread(\n                                lambda: requests.post(\n                                    f"{base_url}/sendMessage",\n                                    json={"chat_id": chat_id, "text": reply},\n                                    timeout=15\n                                )\n                            )'
NEW_BLOCK = '                        # 打字机模式：流式接收 → 按句切段 → 逐句发送（句间 typing）\n                        reply_parts = []\n                        try:\n                            async for _sent in _ask_llm_stream_sentences(client, prompt, temperature=0.8):\n                                _sent = _sent.strip()\n                                if not _sent:\n                                    continue\n                                reply_parts.append(_sent)\n                                await asyncio.to_thread(\n                                    lambda s=_sent: requests.post(\n                                        f"{base_url}/sendChatAction",\n                                        json={"chat_id": chat_id, "action": "typing"},\n                                        timeout=10\n                                    )\n                                )\n                                await asyncio.sleep(min(0.08 * len(_sent), 3.0) + 0.3)\n                                await asyncio.to_thread(\n                                    lambda s=_sent: requests.post(\n                                        f"{base_url}/sendMessage",\n                                        json={"chat_id": chat_id, "text": s},\n                                        timeout=15\n                                    )\n                                )\n                        except Exception as _e:\n                            print(f"❌ 流式回复失败: {_e}")\n\n                        # 流式失败时回退：非流式整段发送\n                        if not reply_parts:\n                            _fallback = await _ask_llm_async(client, prompt, temperature=0.8)\n                            if _fallback:\n                                reply_parts.append(_fallback)\n                                await asyncio.to_thread(\n                                    lambda s=_fallback: requests.post(\n                                        f"{base_url}/sendMessage",\n                                        json={"chat_id": chat_id, "text": s},\n                                        timeout=15\n                                    )\n                                )\n\n                        reply = "\\n".join(reply_parts)\n\n                        if reply:'

with open('heartbeat.py', 'r', encoding='utf-8') as f:
    s = f.read()

assert 'async def async_telegram_polling():' in s, "未找到 TG 轮询函数"
assert OLD_BLOCK in s, "未找到回复代码块"

s = s.replace('async def async_telegram_polling():',
              NEW_FUNC + '\n\n\nasync def async_telegram_polling():', 1)
s = s.replace(OLD_BLOCK, NEW_BLOCK, 1)

with open('heartbeat.py', 'w', encoding='utf-8') as f:
    f.write(s)

print("patched: heartbeat.py (typewriter mode)")
